### ISSUE TITLE
Defining primary suit for responder always fails if opener has a primary suit

### ISSUE THREAD

**Issue by sievers2501** [kdblocher/bridge#137]
Consider the following simple system:

1. 1S: 13-21 S1
a.     2C: 10+ C1

The 2C response generates an error is a conflict between primary suits even though they are in different hands.  

On another note, how would I create this as a unit test?  So far, I can only enter constraints for one hand.

**Comment by kdblocher** [comment]
> On another note, how would I create this as a unit test? So far, I can only enter constraints for one hand.

something like this https://github.com/kdblocher/bridge/blob/2c63b4467454ba8547bf198ef2ccc520e5475c44/src/model/constraints.testdata.ts#L774-L823

**Comment by sievers2501** [comment]
How does the test know that the first bid is opener and the second bid is responder?  Or is that just assumed?  And would that change once we start factoring in opponent's bidding?

**Comment by kdblocher** [comment]
It's assumed, and yes we will have to adjust the data structure.
