### ISSUE TITLE
Choreograph demos for example usages to aid in GUI development and documentation creation

### ISSUE THREAD

**Issue by sievers2501** [kdblocher/bridge#139]
Create a demo script.  

First, show off the hand matching feature.  
1.  Enter sample code for 1H opener.  
2. Enter sample code for 1S opener.  
3. Show off the duplicate feature.  

Second, show off the hand analysis feature.  
1. Define 1NT as 15-17 semiBAL, and then 3C as a 5-7 count with 6 clubs. Look at number of tricks makeable in each case and compare tricks taken in NT (if passed) versus 3 of the minor.

**Comment by kdblocher** [comment]
We should use the project board for this. https://github.com/kdblocher/bridge/projects

**Comment by sievers2501** [comment]
The initial demo will only cover case #1.  The other 4 cases should be broken out into separate use cases when we figure out how to start marketing the different analyses that we are running.

**Comment by kdblocher** [comment]
This is the last issue in the demo milestone. You're on deck @sievers2501

**Comment by sievers2501** [comment]
Ran the demo for KW.  She was quite impressed.  Next up, lots of bug fixes.
