### ISSUE TITLE
Sub-nodes will always be false when parent node using a negation

### ISSUE THREAD

**Issue by sievers2501** [kdblocher/bridge#154]
Enter the following system.

-  1C: 11-20 (C>D or 4333 or 3433) !1N
    -    1N: 6-9

The system will not you check for validity.  If you remove the "!1N" from the parent node, everything works as expected.  It is likely this will be fixed when the SAT binary solver gets merged in.

**Comment by kdblocher** [comment]
> It is likely this will be fixed when the SAT binary solver gets merged in.

I tested this system on the current published app and it appears to work now, so this is likely the case. I'll let you confirm and if you concur, go ahead and close.

**Comment by sievers2501** [comment]
This seems to be working now!  This frees me up to start developing systems again.
