### ISSUE TITLE
Unit test fails when defining both hands to have the card came back with expected value:true instead of false

### ISSUE THREAD

**Issue by sievers2501** [kdblocher/bridge#157]
See unit test   openerResponderSameCard: in the latest push of opener and responder unit tests.  It's possible I didn't define the unit test correctly, as I am not quite familiar with the format of the expansionPathValidTests, but I'm pretty sure it's right.   From the front end, nothing returns, so the program is fine.  It's just that the unit test should return false.

**Comment by sievers2501** [comment]
I am unable to proceed with creation of more unit tests until this issue is fixed.

**Comment by kdblocher** [comment]
I can't find the test `openerResponderSameCard`. Is it possible you had another branch you defined this test in and didn't push it?
