### ISSUE TITLE
Easier syntax for automatic relay acceptance

### ISSUE THREAD

**Issue by sievers2501** [kdblocher/bridge#25]
Currently, if I want to enter a transfer auction, I must write

1N: 12-14 BAL
    2D: 5+h
        2H: 0+

But I really shouldn't even need to put anything after the 2H: if it is an auto-bid.  Again, nothing major, just an oddity of the current parser.

**Comment by sievers2501** [comment]
I can document this.  But if you define a relay bid, then you still need to enter the followup relay acceptance bid underneath that.  Having true is fine.  I'll see if I can figure out how to modify the docs.

**Comment by kdblocher** [comment]
Are you implying bid without a constraint defined as only valid when accepting a relay of some sort (and no additional information implied)? The syntax would simply just be _bid_ (no colon).
