### ISSUE TITLE
Specific honor constraint

### ISSUE THREAD

**Issue by kdblocher** [kdblocher/bridge#56]
Related to #24.

- Ability to specify a suit as "sound", "light", "very light", etc.
- Ability to handle things like the following
```
* 1N:
  * 3m: 6+m KQ+
* 3N: 8+m AKQ+
* 2H: 6+H sound
```

**Comment by eieioAce** [comment]
Weak 2 is usually vulnerability dependent.

**Comment by kdblocher** [comment]
Can combine that with #58
