### ISSUE TITLE
Score table

### ISSUE THREAD

**Issue by kdblocher** [kdblocher/bridge#60]
There are less than 256 possible scores. We can create a precalculated score table (just like the idea in #48) and index them.
Even better it seems that some scores are not possible as par scores (see http://www.rpbridge.net/7a23.htm), but I could see wanting to have all scores available so we can use it to do system statistical analysis down the line.

See https://github.com/kdblocher/bridge/blob/master/src/model/score.testdata.ts for all possible scores.

**Comment by kdblocher** [comment]
Smallint > tinyint

There is one more advantage to indexing - we can know, for instance, how many possible scores are between one score and another.

Does that sway your opinion?

**Comment by sievers2501** [comment]
That can still be done with an index on the main table rather than a separate table.  I see zero advantage to making a second par score table  We aren't normalizing anything by making a separate table.
