### ISSUE TITLE
Formal Definitions of Bridge Terms

### ISSUE THREAD

**Issue by kdblocher** [kdblocher/bridge#71]
Moved to #73 .

**Comment by kdblocher** [comment]
Moved to #73 .

**Comment by sievers2501** [comment]
Is this still open?  If so, what needs to be done in order to close it?

**Comment by kdblocher** [comment]
Tyson and I are working on this together. It is a dependency of the par
score algorithm. Not quite done yet but close.

**Comment by kdblocher** [comment]
Resolved by   #73.
