### ISSUE TITLE
Copying system definition from the Bridge App to GoogleDoc flattens bidding levels

### ISSUE THREAD

**Issue by sievers2501** [kdblocher/bridge#76]
I'm working on a system, and went to save my work over to Google docs.  When I did so, all of the indentations flattened out to one level.  It appear you can copy the other way just fine, from Google docs to the bridge app.  But going TO google docs the tabs are not carried over.  

In once since this isn't urgent, but it does slow me down until we have a better editing method.

**Comment by kdblocher** [comment]
Looks like this is a problem with the text editor tool I chose, as evidenced by this thread: https://github.com/facebook/draft-js/issues/787

I am not tied to the specific editor (or even representation, though something akin to natural language description as we have is ideal for now). I'll look into swapping the editor out for something else, or maybe @aaronobanion can chime in.

For now, you can maintain the system in Google Docs

**Comment by sievers2501** [comment]
Superseded by #168
